//
// --- LISTE DES ÉTUDIANTS ---
//
// Instructions : Modifiez cette liste pour inclure les noms de vos étudiants.
// C'est le seul fichier que vous aurez besoin de changer d'une année sur l'autre.
//
const studentNames = [
    "Riyad ABKARI",
    "Adel ALAHYANI",
    "Tahsan Bin BADAR",
    "Albin BARTH",
    "Johannie BEAUCHA",
    "Ibrahim BELKAID",
    "Mohamed BENMEHA",
    "Adam BERTRAN",
    "Timothé BESSON",
    "Moses BITA",
    "Fériel BOUDJEM",
    "Titouan BOULAU",
    "Lyna-Tounsia BOUSFOU",
    "Thibaut CADOT",
    "Ambre CAILLAUD",
    "Guilhem CASSOU",
    "Myriam CHAIR",
    "Alexandre CHASSAIN",
    "Philomène CONSTAN",
    "Enzo CORREIA",
    "Njock-Mélissa DANG ATI",
    "Gabriel DE LA FAY",
    "Cédric DIABI",
    "Sofiane DKAKI",
    "Valentin DOMBRAY",
    "Gabriel DUPUY",
    "Marwa EL AATTA",
    "Thibaud ÉTOURNE",
    "Lucas FERBOUR",
    "Mathis FERNAND",
    "Mathieu FEROLDI",
    "Raphael FERT",
    "Audrey GEYMET",
    "Priyanga GNANARA",
    "Raphaël GROSJEA",
    "Timothée HUREL",
    "Dany KEBAILI",
    "Luc Rigson KENDINE",
    "Hadi KLEIT",
    "Nitsa KOURILSK",
    "Gianni LANZARO",
    "Davidson LAPOINTE",
    "Gabrielle LEROUXE",
    "Melvyn LUREL",
    "Cloé MEYER",
    "Lokmene OULHOUS",
    "Maud OUSSET",
    "Victor POMMIES",
    "Romain PUPIN",
    "Alexandru PURCSA",
    "Husna SAKAL",
    "Pierre TARDIVEL",
    "Anna TELLIER",
    "Amadou THIOYE",
    "Mathis VOISENET",
    "Victor WATTEBL",
    "Antoine WEGERA"
];